export const FETCH_ROBOTS = "FETCH_ROBOTS";
export const EDIT_MODE = "EDIT_MODE";
export const CLEAR_STATE = "CLEAR_STATE";
export const FETCH_ROBOTS_ASYNC = "FETCH_ROBOTS_ASYNC";
export const FETCH_ROBOT_BY_ID = "FETCH_ROBOT_BY_ID";
export const FETCH_ROBOTS_ASYNC_ERROR = "FETCH_ROBOTS_ASYNC_ERROR";
